### ISSUE TITLE
关于指定订阅文件

### ISSUE THREAD

**Issue by 11pmsleep** [zgao264/AirFly#10]
-f 参数，指定的机场订阅文件，请问这个如何生成，要求什么格式？由于每次请求订阅链接需要翻墙才能访问……所以比较头疼，但是又有点搞不明白这个订阅文件如何搞到本地

**Comment by zgao264** [comment]
订阅文件是base64格式，先把订阅文件下载下来，放到AirFLy同一个目录再指定运行即可
