### ISSUE TITLE
功能建议：访问订阅链接时添加User-Agent

### ISSUE THREAD

**Issue by photkey** [zgao264/AirFly#11]
有的机场各个客户端的订阅连接是同一个网址，在clash和v2rayN里都可以获取到对应的配置文件，应该是通过User-Agent来返回不同的配置文件内容的吧。现在这种机场的订阅链接 不能在AirFly直接使用，猜测是User-Agent的原因。

**Comment by zgao264** [comment]
什么机场，发来看看
