### ISSUE TITLE
期待大佬开源

### ISSUE THREAD

**Issue by Skyline5723** [zgao264/AirFly#2]
期待大佬开源

**Comment by qwe1433223** [comment]
这个如何使用啊，我一分钟内多次访问同一域名，我的IP地址没有变化

**Comment by bsdcpp** [comment]
先感谢大佬。同期待开源啊，否则不敢用啊。

**Comment by jonntd** [comment]
https://github.com/nadoo/glider
用法参考这个

**Comment by bsdcpp** [comment]
> 

glider不适合订阅链接，要多一步手脚，定时从更新链接刷配置。还要重启
