### ISSUE TITLE
如何使用：短时间内请求，依然是同一个IP地址

### ISSUE THREAD

**Issue by qwe1433223** [zgao264/AirFly#3]
命令：.\airfly.exe -l mixed://192.168.0.2:10820 -u https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=xxxxxxxx -s rr

验证地址：https://ip.900cha.com/

结果为同一个IP

**Comment by DistantWolf** [comment]
for /L %i in (1,1,20) do curl ipinfo.io
![image-20230806114239818](https://github.com/zgao264/AirFly/assets/122848952/5b642869-7e03-4193-b57a-c68412ec3eb6)

**Comment by zgao264** [comment]
通过curl测试没有问题
