### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SnowMeteors** [zgao264/AirFly#5]
airfly.exe -l mixed://:10808 -u "https://sub.meimeiyun.top//link/pIElrikcFlLPLz5Z?sub=xxxx"

输出
![image](https://github.com/zgao264/AirFly/assets/47601098/40575399-9efb-4543-9a22-23a4ae44466c)

**Comment by zgao264** [comment]
加我微信zgao264，发我订阅看下，应该试试订阅格式有问题
