### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yuyongxr** [zgao264/AirFly#7]
$ ./airfly -l 7899 -f sub.txt                                                         

   ▄████████  ▄█     ▄████████    ▄████████  ▄█       ▄██   ▄   
  ███    ███ ███    ███    ███   ███    ███ ███       ███   ██▄ 
  ███    ███ ███▌   ███    ███   ███    █▀  ███       ███▄▄▄███ 
  ███    ███ ███▌  ▄███▄▄▄▄██▀  ▄███▄▄▄     ███       ▀▀▀▀▀▀███ 
▀███████████ ███▌ ▀▀███▀▀▀▀▀   ▀▀███▀▀▀     ███       ▄██   ███ 
  ███    ███ ███  ▀███████████   ███        ███       ███   ███ 
  ███    ███ ███    ███    ███   ███        ███▌    ▄ ███   ███ 
  ███    █▀  █▀     ███    ███   ███        █████▄▄██  ▀█████▀  
                    ███    ███              ▀                      version: 0.2
	                  
                         机场订阅一键生成ip代理池，让机场起飞！
                                                                https://zgao.top 
ss://aes-128-gcm:83XvX4Vo%*3a@216.52.183.246:80?plugin=obfs-local%3Bobfs%3Dhttp%3Bobfs-host%3D
ss://chacha20-ietf-poly1305:9e44e9ffe5c2@103.177.33.180:443?plugin=v2ray-plugin%3Bpath%3D%2Fisaifqaagpi%3Bmux%3D8%3Bhost%3Dwtw1000mline004.chilines.club%3Btls
ssr://aes-256-cfb:hGkQ6915tD@iepl-zh.safetelescope.cc:11804?protocol=auth_aes128_md5&protocol_param=Mjc3MjM5OjZQYjFYSU1WYVc&obfs=tls1.2_ticket_auth&obfs_param=ajax.microsoft.com
ss://aes-128-gcm:95869ffd-78ae-4a3f-9531-cb2b4e15ffca@sd.nfsq.me:33351
vmess://668561f4-3332-4b83-a382-da05975040f0@gz.daxun.cyou:26041/?alterID=0
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/nadoo/glider/proxy.convertSS({0x14000214a47?, 0x5d?})
	C:/Users/Administrator/GolandProjects/airfly/proxy/conn.go:419 +0x5dc
github.com/nadoo/glider/proxy.FormatConvert({0x14000214a47, 0x5d})
	C:/Users/Administrator/GolandProjects/airfly/proxy/conn.go:310 +0x74
main.main()
	C:/Users/Administrator/GolandProjects/airfly/main.go:62 +0x39c

**Comment by zgao264** [comment]
zgao264 ，可以把sub.txt 发我看看
